import os
import json
import logging
from datetime import datetime
from flask import Flask, request, jsonify, render_template
from dotenv import load_dotenv
from prompts import PROMPTS
from llm_manager import llm_manager

# Load environment variables from .env file
load_dotenv()

# Configure logging so we can see which provider is being used
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

app = Flask(__name__)

FEEDBACK_FILE = "feedback.json"

def init_feedback_file():
    if not os.path.exists(FEEDBACK_FILE):
        with open(FEEDBACK_FILE, "w") as f:
            json.dump([], f)

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/chat')
def index():
    return render_template('index.html')

@app.route('/terms')
def terms():
    return render_template('terms.html')

@app.route('/privacy')
def privacy():
    return render_template('privacy.html')

@app.route('/providers', methods=['GET'])
def providers():
    """Returns list of currently available (configured) LLM providers."""
    available = llm_manager.get_available_providers()
    return jsonify({"providers": available, "count": len(available)})

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    func = data.get('function')
    style = data.get('style')
    user_input = data.get('input')
    history = data.get('history', [])

    if not all([func, style, user_input]):
        return jsonify({"error": "Missing required fields"}), 400

    if func not in PROMPTS or style not in PROMPTS[func]:
        return jsonify({"error": "Invalid function or style"}), 400

    try:
        # Build system prompt from prompts.py
        system_prompt = "You are a helpful AI assistant."
        formatted_prompt = PROMPTS[func][style].format(input=user_input)

        # Build conversation history for context
        contents = []
        for msg in history:
            contents.append({"role": msg["role"], "text": msg["text"]})

        # Use the LLM manager — it handles fallback automatically
        ai_response, provider_used = llm_manager.generate(
            system_prompt=system_prompt,
            contents=contents,
            user_input=formatted_prompt,
        )

        logger.info(f"Response generated by: {provider_used}")

        return jsonify({
            "response": ai_response,
            "provider": provider_used,
            "prompt_used": formatted_prompt if len(history) == 0 else "Follow-up question"
        })

    except RuntimeError as e:
        error_str = str(e)
        # All providers exhausted
        if "All providers exhausted" in error_str or "No LLM providers" in error_str:
            return jsonify({
                "response": (
                    "⚠️ All AI providers have hit their free usage limits or are not configured!\n\n"
                    "**To fix this, add free API keys to your `.env` file:**\n"
                    "- 🔥 **Groq** (14,400 free req/day): https://console.groq.com\n"
                    "- 🤖 **Gemini**: https://aistudio.google.com/app/apikey\n"
                    "- 🌊 **Cohere**: https://dashboard.cohere.com\n"
                    "- 🤗 **HuggingFace**: https://huggingface.co/settings/tokens\n\n"
                    "Try again later when the limits reset."
                ),
                "provider": "None",
                "prompt_used": "Rate Limit Reached"
            }), 200

        return jsonify({"error": error_str}), 500

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/feedback', methods=['POST'])
def feedback():
    data = request.json
    helpful = data.get('helpful')
    func = data.get('function')
    style = data.get('style')
    user_input = data.get('input')
    ai_response = data.get('response')

    if helpful is None:
         return jsonify({"error": "Missing 'helpful' field"}), 400

    feedback_entry = {
        "timestamp": datetime.now().isoformat(),
        "function": func,
        "style": style,
        "input": user_input,
        "response": ai_response,
        "helpful": helpful
    }

    try:
        init_feedback_file()
        with open(FEEDBACK_FILE, "r") as f:
            feedbacks = json.load(f)
        
        feedbacks.append(feedback_entry)

        with open(FEEDBACK_FILE, "w") as f:
            json.dump(feedbacks, f, indent=4)
            
        return jsonify({"message": "Feedback saved successfully"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    init_feedback_file()
    logger.info(f"Available LLM providers: {llm_manager.get_available_providers()}")
    app.run(debug=True, port=5000)
